n=input("Digite uma frase")
b=len(n)
c=n.strip()
d=len(c)
e=n.count("a")
f=n.count("e")
h=n.count("s")
i=n.split()
j=len(i)
print(f"Frase limpa: {c}\nCaracteres com bordas: {b}\nCaracteres sem bordas: {d}\nNúmero de palavras: {j}\nQuantidade de letra A: {e}\nQuantidade de letras E: {f}\nQuantidade de letras S: {h}\nSoma das três letras: {e+f+h}\nDiferença entre caracteres sem bordas e número de palavras: {d-j}")